// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcKIQW0DAM5h9nqwPltvdG_SD57BpQ3Go',
    appId: '1:718649070548:web:e033114e2e1ff0b3f83c41',
    messagingSenderId: '718649070548',
    projectId: 'notesapp-a246e',
    authDomain: 'notesapp-a246e.firebaseapp.com',
    storageBucket: 'notesapp-a246e.firebasestorage.app',
    measurementId: 'G-6QPF8HHDRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO_4A3FbTE7f-jprWiu3_8_GK6trfZUOQ',
    appId: '1:718649070548:android:2ae3a692ff22c5e7f83c41',
    messagingSenderId: '718649070548',
    projectId: 'notesapp-a246e',
    storageBucket: 'notesapp-a246e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0X4lGRzuBJk4aCD1rMRHfc7x-Os7q6-U',
    appId: '1:718649070548:ios:cc00becb261816a7f83c41',
    messagingSenderId: '718649070548',
    projectId: 'notesapp-a246e',
    storageBucket: 'notesapp-a246e.firebasestorage.app',
    iosClientId: '718649070548-ipn80758u7vmpj7legbjibd75bjj7d40.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0X4lGRzuBJk4aCD1rMRHfc7x-Os7q6-U',
    appId: '1:718649070548:ios:cc00becb261816a7f83c41',
    messagingSenderId: '718649070548',
    projectId: 'notesapp-a246e',
    storageBucket: 'notesapp-a246e.firebasestorage.app',
    iosClientId: '718649070548-ipn80758u7vmpj7legbjibd75bjj7d40.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcKIQW0DAM5h9nqwPltvdG_SD57BpQ3Go',
    appId: '1:718649070548:web:3914017e6d2d219ff83c41',
    messagingSenderId: '718649070548',
    projectId: 'notesapp-a246e',
    authDomain: 'notesapp-a246e.firebaseapp.com',
    storageBucket: 'notesapp-a246e.firebasestorage.app',
    measurementId: 'G-KSPGQW6PQ7',
  );
}
